#! /bin/sh

##
# PySub
# https://github.com/leosartaj/PySub.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

# installed directory
INSTALL_DIR='/usr/local/PySub'

help_pysub()
{
  echo "Usage: $0"
  echo "  -h : Displays this help"
  echo "  [download] [filename/directory] : Download the subtitle/subtitles"
  exit 1
}

if [ $# -ne 2 ]; then
  help_pysub
fi

# Parse arguments
while getopts h opt
do
  case "$opt" in
      h) help_pysub;;
      \?) help_pysub;;
  esac
done

if [ $# -eq 2 ]; then
  if [ "$1" = "download" ]; then
    python2.7 "$INSTALL_DIR/download.py" "$2" 
  else
    help_pysub
  fi
fi
