#! /bin/sh

##
# PySub
# https://github.com/leosartaj/PySub.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

# installed directory
INSTALL_DIR='/usr/local/pysub'

help_pysub()
{
  echo "Usage: $0"
  echo "  -h : Displays this help"
  exit 1
}

# If no command-line args, display help and exit
if [ $# -lt 1 ]; then
  help_pysub
fi

# If more than one command line argument, display help and exit
if [ $# -gt 3 ]; then
  help_pysub
fi

# Parse arguments
while getopts h opt
do
  case "$opt" in
      h) help_pysub;;
      \?) help_pysub;;
  esac
done
